import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Toaster } from 'react-hot-toast';
import './globals.css';

export const metadata: Metadata = {
  icons: {
    icon: '/logo.png', // /public path
  },
  title: 'Nikke Blabla',
  description: 'Generated by create next app',
};
const sourceHanSans = localFont({
  src: '../assets/fonts/PingFang Heavy.ttf',
  display: 'swap',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={sourceHanSans.className}>
        <Toaster
          toastOptions={{
            style: {
              zIndex: 9999,
            },
          }}
        />
        <div className="app">{children}</div>
      </body>
    </html>
  );
}
