import type {Metadata} from 'next';
import {Toaster} from 'react-hot-toast';
import './globals.css';
import '@fontsource-variable/noto-sans-sc';

export const metadata: Metadata = {
    icons: {
        icon: '/logo.png', // /public path
    },
    title: 'Nikke Blabla',
    description: 'Generated by create next app',
};


export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body>
        <Toaster
            toastOptions={{
                style: {
                    zIndex: 9999,
                },
            }}
        />
        <div className="app">{children}</div>
        </body>
        </html>
    );
}
